// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: session.proto
// Original file comments:
// PurrBoss central session API, major version 1.
//
// Wire identity:
//
//   package: purrboss.v1
//   service: purrboss.v1.SessionService
//
// The package is the authoritative API version marker. The file remains
// session.proto because its name describes the API domain. Do not add V1 to
// the service name: purrboss.v1.SessionServiceV1 would encode the version
// twice.
//
// Compatible additions stay in purrboss.v1. Never change the meaning or wire
// type of an existing field number. Reserve removed field numbers and names
// so they can never be reused. An incompatible contract must use a new
// package such as purrboss.v2 and run beside v1 while clients migrate.
//
// This repository currently has one API version, so its canonical file is
// protos/session.proto. If multiple major versions coexist, prefer version
// directories over filename suffixes:
//
//   protos/v1/session.proto
//   protos/v2/session.proto
//
// Preserve the canonical import path "session.proto" if that layout is
// introduced after clients have started importing this file.
//
// System context:
//
//   +--------+              +-------------------+
//   | Mobile | -- key ----> | Main App Instance |
//   +--------+              +---------+---------+
//                                     |
//                                     v
//                           +--------------------+
//                           | Local SQLite Cache |
//                           +----+----------+----+
//                                |          |
//                          hit   |          | miss/stale
//                                v          v
//                         use session  ValidateSession
//                                          |
//                                          v
//                                     +----------+
//                                     | PurrBoss |
//                                     +----+-----+
//                                          |
//                                          v
//                                +-------------------+
//                                | Persistent SQLite |
//                                +-------------------+
//
// PurrBoss is the authoritative source. A main app's SQLite cache is local,
// ephemeral, and outside this API.
//
#ifndef GRPC_session_2eproto__INCLUDED
#define GRPC_session_2eproto__INCLUDED

#include "session.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace purrboss {
namespace v1 {

// Authoritative session operations used by horizontally scaled main apps.
//
// Calls are intended for private service-to-service networking. A caller may
// attach these lowercase gRPC metadata entries:
//
//   x-machine-id   Runtime instance ID; enables active-instance tracking.
//   x-internal-ip  Private address used by the planned webhook fan-out.
//   x-region       Deployment region containing the main app instance.
//
// Every RPC refreshes active_instances when x-machine-id is present. Omitting
// it does not make the session operation invalid; it only skips tracking.
class SessionService final {
 public:
  static constexpr char const* service_full_name() {
    return "purrboss.v1.SessionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Creates a new opaque session and persists it before returning.
    //
    //   Main App              PurrBoss                 SQLite
    //      | CreateSession       |                        |
    //      |-------------------->|                        |
    //      |                     | INSERT session         |
    //      |                     |----------------------->|
    //      |                     |<-----------------------| committed
    //      |<--------------------| key + expiration       |
    //
    // This operation is not idempotent: retrying a successful request creates
    // another session. A future idempotency key would require a new request
    // field and persistence rule.
    virtual ::grpc::Status CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::purrboss::v1::CreateSessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::CreateSessionResponse>> AsyncCreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::CreateSessionResponse>>(AsyncCreateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::CreateSessionResponse>> PrepareAsyncCreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::CreateSessionResponse>>(PrepareAsyncCreateSessionRaw(context, request, cq));
    }
    // Reads authoritative state after a local cache miss or stale cache entry.
    //
    //   Main App          Local Cache          PurrBoss          SQLite
    //      | lookup            |                  |                |
    //      |------------------>|                  |                |
    //      |<------------------| hit              |                |
    //      | use cached session|                  |                |
    //      |                   |                  |                |
    //      |<------------------| miss/stale       |                |
    //      | ValidateSession -------------------->|                |
    //      |                                      | SELECT session |
    //      |                                      |--------------->|
    //      |                                      |<---------------|
    //      |<-------------------------------------| result          |
    //
    // The cache-hit path ends without a central RPC. The miss/stale path
    // continues with ValidateSession.
    //
    // Invalid session states are normal responses, not transport errors.
    virtual ::grpc::Status ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::purrboss::v1::ValidateSessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::ValidateSessionResponse>> AsyncValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::ValidateSessionResponse>>(AsyncValidateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::ValidateSessionResponse>> PrepareAsyncValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::ValidateSessionResponse>>(PrepareAsyncValidateSessionRaw(context, request, cq));
    }
    // Soft-revokes a session by setting revoked_at and reason_revoked.
    //
    //   Main App              PurrBoss                 SQLite
    //      | InvalidateSession  |                        |
    //      |------------------->|                        |
    //      |                    | UPDATE revoked_at      |
    //      |                    |----------------------->|
    //      |                    |<-----------------------| committed
    //      |<-------------------| success                |
    //                           |
    //                           + - planned webhook - -> recent main apps
    //
    // Repeating the call is safe. PurrBoss preserves the first revocation time
    // and reason. Webhook delivery is a server-side concern and is not part of
    // this RPC response.
    virtual ::grpc::Status InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::purrboss::v1::InvalidateSessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::InvalidateSessionResponse>> AsyncInvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::InvalidateSessionResponse>>(AsyncInvalidateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::InvalidateSessionResponse>> PrepareAsyncInvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::InvalidateSessionResponse>>(PrepareAsyncInvalidateSessionRaw(context, request, cq));
    }
    // Checks application-level availability and records caller activity.
    //
    //   Main App              PurrBoss            active_instances
    //      | Ping                |                        |
    //      |-------------------->|                        |
    //      |                     | UPSERT caller          |
    //      |                     |----------------------->|
    //      |<--------------------| ok + server time       |
    //
    // PurrBoss also exposes the standard gRPC health service.
    virtual ::grpc::Status Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::purrboss::v1::PingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::PingResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::PingResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Creates a new opaque session and persists it before returning.
      //
      //   Main App              PurrBoss                 SQLite
      //      | CreateSession       |                        |
      //      |-------------------->|                        |
      //      |                     | INSERT session         |
      //      |                     |----------------------->|
      //      |                     |<-----------------------| committed
      //      |<--------------------| key + expiration       |
      //
      // This operation is not idempotent: retrying a successful request creates
      // another session. A future idempotency key would require a new request
      // field and persistence rule.
      virtual void CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Reads authoritative state after a local cache miss or stale cache entry.
      //
      //   Main App          Local Cache          PurrBoss          SQLite
      //      | lookup            |                  |                |
      //      |------------------>|                  |                |
      //      |<------------------| hit              |                |
      //      | use cached session|                  |                |
      //      |                   |                  |                |
      //      |<------------------| miss/stale       |                |
      //      | ValidateSession -------------------->|                |
      //      |                                      | SELECT session |
      //      |                                      |--------------->|
      //      |                                      |<---------------|
      //      |<-------------------------------------| result          |
      //
      // The cache-hit path ends without a central RPC. The miss/stale path
      // continues with ValidateSession.
      //
      // Invalid session states are normal responses, not transport errors.
      virtual void ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Soft-revokes a session by setting revoked_at and reason_revoked.
      //
      //   Main App              PurrBoss                 SQLite
      //      | InvalidateSession  |                        |
      //      |------------------->|                        |
      //      |                    | UPDATE revoked_at      |
      //      |                    |----------------------->|
      //      |                    |<-----------------------| committed
      //      |<-------------------| success                |
      //                           |
      //                           + - planned webhook - -> recent main apps
      //
      // Repeating the call is safe. PurrBoss preserves the first revocation time
      // and reason. Webhook delivery is a server-side concern and is not part of
      // this RPC response.
      virtual void InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Checks application-level availability and records caller activity.
      //
      //   Main App              PurrBoss            active_instances
      //      | Ping                |                        |
      //      |-------------------->|                        |
      //      |                     | UPSERT caller          |
      //      |                     |----------------------->|
      //      |<--------------------| ok + server time       |
      //
      // PurrBoss also exposes the standard gRPC health service.
      virtual void Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::CreateSessionResponse>* AsyncCreateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::CreateSessionResponse>* PrepareAsyncCreateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::ValidateSessionResponse>* AsyncValidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::ValidateSessionResponse>* PrepareAsyncValidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::InvalidateSessionResponse>* AsyncInvalidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::InvalidateSessionResponse>* PrepareAsyncInvalidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::purrboss::v1::PingResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::purrboss::v1::CreateSessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>> AsyncCreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>>(AsyncCreateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>> PrepareAsyncCreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>>(PrepareAsyncCreateSessionRaw(context, request, cq));
    }
    ::grpc::Status ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::purrboss::v1::ValidateSessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>> AsyncValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>>(AsyncValidateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>> PrepareAsyncValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>>(PrepareAsyncValidateSessionRaw(context, request, cq));
    }
    ::grpc::Status InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::purrboss::v1::InvalidateSessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>> AsyncInvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>>(AsyncInvalidateSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>> PrepareAsyncInvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>>(PrepareAsyncInvalidateSessionRaw(context, request, cq));
    }
    ::grpc::Status Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::purrboss::v1::PingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response, std::function<void(::grpc::Status)>) override;
      void ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response, std::function<void(::grpc::Status)>) override;
      void InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response, std::function<void(::grpc::Status)>) override;
      void Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>* AsyncCreateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>* PrepareAsyncCreateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>* AsyncValidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>* PrepareAsyncValidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>* AsyncInvalidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>* PrepareAsyncInvalidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateSession_;
    const ::grpc::internal::RpcMethod rpcmethod_ValidateSession_;
    const ::grpc::internal::RpcMethod rpcmethod_InvalidateSession_;
    const ::grpc::internal::RpcMethod rpcmethod_Ping_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Creates a new opaque session and persists it before returning.
    //
    //   Main App              PurrBoss                 SQLite
    //      | CreateSession       |                        |
    //      |-------------------->|                        |
    //      |                     | INSERT session         |
    //      |                     |----------------------->|
    //      |                     |<-----------------------| committed
    //      |<--------------------| key + expiration       |
    //
    // This operation is not idempotent: retrying a successful request creates
    // another session. A future idempotency key would require a new request
    // field and persistence rule.
    virtual ::grpc::Status CreateSession(::grpc::ServerContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response);
    // Reads authoritative state after a local cache miss or stale cache entry.
    //
    //   Main App          Local Cache          PurrBoss          SQLite
    //      | lookup            |                  |                |
    //      |------------------>|                  |                |
    //      |<------------------| hit              |                |
    //      | use cached session|                  |                |
    //      |                   |                  |                |
    //      |<------------------| miss/stale       |                |
    //      | ValidateSession -------------------->|                |
    //      |                                      | SELECT session |
    //      |                                      |--------------->|
    //      |                                      |<---------------|
    //      |<-------------------------------------| result          |
    //
    // The cache-hit path ends without a central RPC. The miss/stale path
    // continues with ValidateSession.
    //
    // Invalid session states are normal responses, not transport errors.
    virtual ::grpc::Status ValidateSession(::grpc::ServerContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response);
    // Soft-revokes a session by setting revoked_at and reason_revoked.
    //
    //   Main App              PurrBoss                 SQLite
    //      | InvalidateSession  |                        |
    //      |------------------->|                        |
    //      |                    | UPDATE revoked_at      |
    //      |                    |----------------------->|
    //      |                    |<-----------------------| committed
    //      |<-------------------| success                |
    //                           |
    //                           + - planned webhook - -> recent main apps
    //
    // Repeating the call is safe. PurrBoss preserves the first revocation time
    // and reason. Webhook delivery is a server-side concern and is not part of
    // this RPC response.
    virtual ::grpc::Status InvalidateSession(::grpc::ServerContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response);
    // Checks application-level availability and records caller activity.
    //
    //   Main App              PurrBoss            active_instances
    //      | Ping                |                        |
    //      |-------------------->|                        |
    //      |                     | UPSERT caller          |
    //      |                     |----------------------->|
    //      |<--------------------| ok + server time       |
    //
    // PurrBoss also exposes the standard gRPC health service.
    virtual ::grpc::Status Ping(::grpc::ServerContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateSession() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateSession(::grpc::ServerContext* context, ::purrboss::v1::CreateSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::purrboss::v1::CreateSessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ValidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ValidateSession() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ValidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidateSession(::grpc::ServerContext* context, ::purrboss::v1::ValidateSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::purrboss::v1::ValidateSessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InvalidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InvalidateSession() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_InvalidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InvalidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInvalidateSession(::grpc::ServerContext* context, ::purrboss::v1::InvalidateSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::purrboss::v1::InvalidateSessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ping() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::purrboss::v1::PingRequest* request, ::grpc::ServerAsyncResponseWriter< ::purrboss::v1::PingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateSession<WithAsyncMethod_ValidateSession<WithAsyncMethod_InvalidateSession<WithAsyncMethod_Ping<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateSession() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response) { return this->CreateSession(context, request, response); }));}
    void SetMessageAllocatorFor_CreateSession(
        ::grpc::MessageAllocator< ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ValidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ValidateSession() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response) { return this->ValidateSession(context, request, response); }));}
    void SetMessageAllocatorFor_ValidateSession(
        ::grpc::MessageAllocator< ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ValidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ValidateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InvalidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InvalidateSession() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response) { return this->InvalidateSession(context, request, response); }));}
    void SetMessageAllocatorFor_InvalidateSession(
        ::grpc::MessageAllocator< ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InvalidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InvalidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InvalidateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response) { return this->Ping(context, request, response); }));}
    void SetMessageAllocatorFor_Ping(
        ::grpc::MessageAllocator< ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateSession<WithCallbackMethod_ValidateSession<WithCallbackMethod_InvalidateSession<WithCallbackMethod_Ping<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateSession() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ValidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ValidateSession() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ValidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InvalidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InvalidateSession() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_InvalidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InvalidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ping() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateSession() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ValidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ValidateSession() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ValidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidateSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InvalidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InvalidateSession() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_InvalidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InvalidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInvalidateSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ping() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateSession() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ValidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ValidateSession() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ValidateSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_ValidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ValidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ValidateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InvalidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InvalidateSession() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InvalidateSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_InvalidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InvalidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InvalidateSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateSession() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse>* streamer) {
                       return this->StreamedCreateSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::CreateSessionRequest* /*request*/, ::purrboss::v1::CreateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::purrboss::v1::CreateSessionRequest,::purrboss::v1::CreateSessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ValidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ValidateSession() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse>* streamer) {
                       return this->StreamedValidateSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ValidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ValidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::ValidateSessionRequest* /*request*/, ::purrboss::v1::ValidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedValidateSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::purrboss::v1::ValidateSessionRequest,::purrboss::v1::ValidateSessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InvalidateSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InvalidateSession() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse>* streamer) {
                       return this->StreamedInvalidateSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InvalidateSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InvalidateSession(::grpc::ServerContext* /*context*/, const ::purrboss::v1::InvalidateSessionRequest* /*request*/, ::purrboss::v1::InvalidateSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInvalidateSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::purrboss::v1::InvalidateSessionRequest,::purrboss::v1::InvalidateSessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ping() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse>* streamer) {
                       return this->StreamedPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::purrboss::v1::PingRequest* /*request*/, ::purrboss::v1::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::purrboss::v1::PingRequest,::purrboss::v1::PingResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateSession<WithStreamedUnaryMethod_ValidateSession<WithStreamedUnaryMethod_InvalidateSession<WithStreamedUnaryMethod_Ping<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateSession<WithStreamedUnaryMethod_ValidateSession<WithStreamedUnaryMethod_InvalidateSession<WithStreamedUnaryMethod_Ping<Service > > > > StreamedService;
};

}  // namespace v1
}  // namespace purrboss


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_session_2eproto__INCLUDED
