// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: session.proto

#include "session.pb.h"
#include "session.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace purrboss {
namespace v1 {

static const char* SessionService_method_names[] = {
  "/purrboss.v1.SessionService/CreateSession",
  "/purrboss.v1.SessionService/ValidateSession",
  "/purrboss.v1.SessionService/InvalidateSession",
  "/purrboss.v1.SessionService/Ping",
};

std::unique_ptr< SessionService::Stub> SessionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SessionService::Stub> stub(new SessionService::Stub(channel, options));
  return stub;
}

SessionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateSession_(SessionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ValidateSession_(SessionService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InvalidateSession_(SessionService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ping_(SessionService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SessionService::Stub::CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::purrboss::v1::CreateSessionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateSession_, context, request, response);
}

void SessionService::Stub::async::CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSession_, context, request, response, std::move(f));
}

void SessionService::Stub::async::CreateSession(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>* SessionService::Stub::PrepareAsyncCreateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::purrboss::v1::CreateSessionResponse, ::purrboss::v1::CreateSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::CreateSessionResponse>* SessionService::Stub::AsyncCreateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::CreateSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SessionService::Stub::ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::purrboss::v1::ValidateSessionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ValidateSession_, context, request, response);
}

void SessionService::Stub::async::ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateSession_, context, request, response, std::move(f));
}

void SessionService::Stub::async::ValidateSession(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>* SessionService::Stub::PrepareAsyncValidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::purrboss::v1::ValidateSessionResponse, ::purrboss::v1::ValidateSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ValidateSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::ValidateSessionResponse>* SessionService::Stub::AsyncValidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::ValidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidateSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SessionService::Stub::InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::purrboss::v1::InvalidateSessionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InvalidateSession_, context, request, response);
}

void SessionService::Stub::async::InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InvalidateSession_, context, request, response, std::move(f));
}

void SessionService::Stub::async::InvalidateSession(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InvalidateSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>* SessionService::Stub::PrepareAsyncInvalidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::purrboss::v1::InvalidateSessionResponse, ::purrboss::v1::InvalidateSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InvalidateSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::InvalidateSessionResponse>* SessionService::Stub::AsyncInvalidateSessionRaw(::grpc::ClientContext* context, const ::purrboss::v1::InvalidateSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInvalidateSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SessionService::Stub::Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::purrboss::v1::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void SessionService::Stub::async::Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void SessionService::Stub::async::Ping(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>* SessionService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::purrboss::v1::PingResponse, ::purrboss::v1::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::purrboss::v1::PingResponse>* SessionService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::purrboss::v1::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

SessionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionService::Service, ::purrboss::v1::CreateSessionRequest, ::purrboss::v1::CreateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SessionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::purrboss::v1::CreateSessionRequest* req,
             ::purrboss::v1::CreateSessionResponse* resp) {
               return service->CreateSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionService::Service, ::purrboss::v1::ValidateSessionRequest, ::purrboss::v1::ValidateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SessionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::purrboss::v1::ValidateSessionRequest* req,
             ::purrboss::v1::ValidateSessionResponse* resp) {
               return service->ValidateSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionService::Service, ::purrboss::v1::InvalidateSessionRequest, ::purrboss::v1::InvalidateSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SessionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::purrboss::v1::InvalidateSessionRequest* req,
             ::purrboss::v1::InvalidateSessionResponse* resp) {
               return service->InvalidateSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SessionService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SessionService::Service, ::purrboss::v1::PingRequest, ::purrboss::v1::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SessionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::purrboss::v1::PingRequest* req,
             ::purrboss::v1::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

SessionService::Service::~Service() {
}

::grpc::Status SessionService::Service::CreateSession(::grpc::ServerContext* context, const ::purrboss::v1::CreateSessionRequest* request, ::purrboss::v1::CreateSessionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionService::Service::ValidateSession(::grpc::ServerContext* context, const ::purrboss::v1::ValidateSessionRequest* request, ::purrboss::v1::ValidateSessionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionService::Service::InvalidateSession(::grpc::ServerContext* context, const ::purrboss::v1::InvalidateSessionRequest* request, ::purrboss::v1::InvalidateSessionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SessionService::Service::Ping(::grpc::ServerContext* context, const ::purrboss::v1::PingRequest* request, ::purrboss::v1::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace purrboss
}  // namespace v1
#include <grpcpp/ports_undef.inc>

